services:
    idci_simpleschedule.type.week_days:
        class: IDCI\Bundle\SimpleScheduleBundle\Form\Type\WeekDaysType
        tags:
            - { name: form.type, alias: week_days }

    idci_simpleschedule.type.meta:
        class: IDCI\Bundle\SimpleScheduleBundle\Form\Type\MetaType
        tags:
            - { name: form.type, alias: meta }
