services:
    idci_simpleschedule.type.week_days:
        class: IDCI\Bundle\SimpleScheduleBundle\Form\Type\WeekDaysType
        tags:
            - { name: form.type, alias: week_days }

    idci_simpleschedule.type.duration:
        class: IDCI\Bundle\SimpleScheduleBundle\Form\Type\DurationType
        tags:
            - { name: form.type, alias: duration }
